src/objects/Batch_Prep__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Prep</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Prep</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Result__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Prep__c</fullName>
        <label>Batch Prep</label>
        <referenceTo>Batch_Prep__c</referenceTo>
        <relationshipLabel>Batch Results</relationshipLabel>
        <relationshipName>Batch_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>If applicable, a text description pertaining to the Score can be defined</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emotions_Count__c</fullName>
        <inlineHelpText>The number of emotions used to calculate the score</inlineHelpText>
        <label>Emotions Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <inlineHelpText>The score result from the Batch operation</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <inlineHelpText>The Date/Time being scored</inlineHelpText>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Result</label>
    <nameField>
        <displayFormat>BR-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Emotion__c.object
<CustomObject>
    <fields>
        <fullName>Mood_Number__c</fullName>
        <label>Mood Number</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mood__c</fullName>
        <label>Mood</label>
        <picklist>
            <picklistValues>
                <fullName>Happy</fullName>
                <color>#33FF33</color>
            </picklistValues>
            <picklistValues>
                <fullName>Sad</fullName>
                <color>#3333FF</color>
            </picklistValues>
            <picklistValues>
                <fullName>Bored</fullName>
                <color>#BBBBBB</color>
            </picklistValues>
            <picklistValues>
                <fullName>Confused</fullName>
                <color>#996633</color>
            </picklistValues>
            <picklistValues>
                <fullName>Excited</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Silly</fullName>
                <color>#F3D904</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Emotion</label>
    <nameField>
        <displayFormat>emo{000000}</displayFormat>
        <label>Emotion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Emotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batchScoring.cls
global class batchScoring implements Database.Batchable<SObject>, Database.Stateful {

    /*
    * To Run:
    
    batchScoring job = new batchScoring();
    job.batchPrepId = batchPrepId;
    Id processId = Database.executeBatch(job, 20);
    
    */
    
    public class BatchException extends Exception {}
    global String batchPrepId; // Batch Prep record Id
    
    // start - Method required by the framework to start the job execution.
    global Database.QueryLocator start(Database.BatchableContext ctx) {
        
        if (batchPrepId == null) { throw new BatchException('A record Id is required'); }
        
        // Select all Batch Result records linked to the Batch Prep record
        String theQuery = 'SELECT Id, Timestamp__c, Score__c, Emotions_Count__c, Description__c, Batch_Prep__c  FROM Batch_Result__c where Batch_Prep__c = \'' + batchPrepId + '\'';
        
        // Set the queryLocator
        return Database.getQueryLocator(theQuery);
        
    }
    
    // execute - Method required by the framework to process the records returned by the query locator created in the start method.
    global void execute(Database.BatchableContext ctx, List<SObject> sobjects) {
        
        for (sObject so : sobjects){
        
            // Get the working Timestamp
            Datetime wrkTimeStart = (datetime)so.get('Timestamp__c');
            Datetime wrkTimeEnd = (datetime)so.get('Timestamp__c');
            wrkTimeEnd = wrkTimeEnd.addSeconds(59);
            
            system.debug(wrkTimeStart);
            system.debug(wrkTimeEnd);
            
            // Query Emotion records in that Timestamp
            List<Emotion__c> emos = [select id, Mood__c, Mood_Number__c from Emotion__c where CreatedDate >= :wrkTimeStart and CreatedDate <= :wrkTimeEnd];
            Decimal sum = 0;
            for (Emotion__c emo : emos){
                sum += emo.Mood_Number__c;
            }
            
            so.put('Emotions_Count__c', emos.size());
            if (emos.size() == 0){
                so.put('Score__c', 0);
            } else {
                so.put('Score__c', sum / emos.size());
            }
        
        }
        
        update sobjects;
        
    }
    
    // finish - Method required and invoked by the framework when a batch job is done.
    global void finish(Database.BatchableContext ctx){
        
        for (Batch_Prep__c bp : [select id, Status__c from Batch_Prep__c where id = :batchPrepId limit 1]){
            bp.Status__c = 'Complete';
            update bp;
        }
        
    }
    
}