src/objects/Batch_Prep__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Job_ID__c</fullName>
        <label>Batch Job ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Results__c</fullName>
        <formula>HYPERLINK(&quot;/00OA00000044gnW?pv0=&quot; &amp; Id, &quot;Report on Results&quot;,&quot;_blank&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Results</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Batch Prep</label>
    <nameField>
        <displayFormat>BP-{00000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Prep</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Batch_Result__c.object
<CustomObject>
    <fields>
        <fullName>Batch_Prep__c</fullName>
        <label>Batch Prep</label>
        <referenceTo>Batch_Prep__c</referenceTo>
        <relationshipLabel>Batch Results</relationshipLabel>
        <relationshipName>Batch_Results</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Emotions_Count__c</fullName>
        <inlineHelpText>The number of emotions used to calculate the score</inlineHelpText>
        <label>Emotions Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Minute_Number__c</fullName>
        <label>Minute Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <inlineHelpText>The score result from the Batch operation</inlineHelpText>
        <label>Score</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Timestamp__c</fullName>
        <inlineHelpText>The Date/Time being scored</inlineHelpText>
        <label>Timestamp</label>
        <type>DateTime</type>
    </fields>
    <label>Batch Result</label>
    <nameField>
        <displayFormat>BR-{000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmoVizController.cls
global class EmoVizController {
	
	public Batch_Prep__c batchPrep {get; private set;}
	
	public String selectedBatch {get; set;}
	
	public EmoVizController() {
		
		if(ApexPages.CurrentPage().getParameters().containsKey('bpid')) {
			selectedBatch = ApexPages.CurrentPage().getParameters().get('bpid');
		}
		
	}
	
	public List<SelectOption> getBatchOptions() {
		
		List<SelectOption> opts = new List<SelectOption>();
		
		for(Batch_Prep__c bp : [SELECT Id, Name, Status__c, Start_Time__c, End_Time__c FROM Batch_Prep__c WHERE Status__c = 'Complete']) {
			opts.add(new SelectOption(bp.Id, bp.Name));
		}
		
		return opts;
		
	}
	
	public Batch_Prep__c getBatch() {
		
		if(selectedBatch != null) {
			return [SELECT Id, Name, Batch_Job_Id__c, Start_Time__c, End_Time__c, Results__c, 
					(SELECT Id, Name, Emotions_Count__c, Minute_Number__c, Score__c, Timestamp__c FROM Batch_Results__r)
					FROM Batch_Prep__c WHERE Id = :selectedBatch];
		}
		
		return null;
		
	}
	
	@RemoteAction
	global static Batch_Result__c[] getResults(String batchPrepId) {
		
		return [SELECT Id, Name, Emotions_Count__c, Minute_Number__c, Score__c, Timestamp__c, Batch_Prep__c 
				FROM Batch_Result__c
				WHERE Batch_Prep__c = :batchPrepId
				ORDER BY Minute_Number__c];

	}
	

}